version: '3.8'

services:
  # Nginx reverse proxy
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - helpdesk-network

  # Frontend service (React/TypeScript)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - PUBLIC_API_URL=/api
    environment:
      - NODE_ENV=production
      - PUBLIC_API_URL=/api
    networks:
      - helpdesk-network
    depends_on:
      - backend

  # Backend API service (Go)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORTAL_BASE_URL=${PORTAL_BASE_URL}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=disable
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_PROVIDER=${EMAIL_PROVIDER}
      - EMAIL_API_KEY=${EMAIL_API_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - helpdesk-network

  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - helpdesk-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MinIO for file storage (S3 compatible)
  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
      - MINIO_SERVER_URL=http://localhost:9000
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    networks:
      - helpdesk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  helpdesk-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data: