# render.yaml
# ==================================================
# Infrastructure definition for the IT Helpdesk System on Render.
# Place this file in the root of your repository.
# ** UPDATED: Added 'value: ""' for env vars set via dashboard **
# ==================================================

services:
  # Nginx Reverse Proxy (Public Web Service)
  - name: nginx # Service name (can be anything descriptive)
    type: web # Exposed to the internet
    env: docker # Specify Docker environment
    dockerfilePath: ./nginx/Dockerfile # Path to Dockerfile relative to repo root
    envVars:
      - key: NGINX_PORT # Nginx usually listens on 80 by default inside container
        value: 80
      # Add any other env vars needed by nginx container specifically

  # Frontend Service (Private Service - served via Nginx)
  - name: frontend
    type: pserv # Private service, not directly exposed
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    # Define build arguments if needed (like PUBLIC_API_URL, though Nginx handles this)
    # dockerBuildArgs:
    #   PUBLIC_API_URL: /api # Or your actual API path if different
    # No start command needed if defined in Dockerfile CMD
    # No ports needed as it's accessed internally by Nginx

  # Backend Service (Private Service - accessed via Nginx proxy)
  - name: backend
    type: pserv # Private service
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      # --- Database URL (Injected by Render) ---
      - key: DATABASE_URL
        fromDatabase:
          name: it-helpdesk-db # Must match the database name defined below
          property: connectionString
      # --- Secrets (Values MUST be set in Render Dashboard Environment) ---
      - key: JWT_SECRET
        value: "" # Add empty value, will be overridden by dashboard secret
      - key: S3_ACCESS_KEY # Your Backblaze B2 Key ID
        value: "" # Add empty value, will be overridden by dashboard secret
      - key: S3_SECRET_KEY # Your Backblaze B2 Application Key
        value: "" # Add empty value, will be overridden by dashboard secret
      - key: RESEND_API_KEY # Your Resend API Key
        value: "" # Add empty value, will be overridden by dashboard secret
      # --- Non-Secrets (Values MUST be set in Render Dashboard Environment) ---
      - key: PORT # Internal port the Go app listens on
        value: 8080 # Keep this default internal port
      - key: PORTAL_BASE_URL # Value to be set in Render UI
        value: "" # Add empty value, will be overridden by dashboard setting
      - key: EMAIL_FROM # Value to be set in Render UI
        value: "" # Add empty value, will be overridden by dashboard setting
      # --- Backblaze B2 Configuration (Values MUST be set in Render Dashboard Environment) ---
      - key: S3_ENDPOINT
        value: "" # Add empty value, will be overridden by dashboard setting
      - key: S3_REGION
        value: "" # Add empty value, will be overridden by dashboard setting
      - key: S3_BUCKET
        value: "" # Add empty value, will be overridden by dashboard setting
      - key: S3_DISABLE_SSL # Keep this as a direct value
        value: false # Backblaze B2 uses HTTPS
      # Add other backend env vars as needed (CACHE_*, etc.)
      # Example for Cache (if using Redis - uncomment and set REDIS_URL secret)
      # - key: CACHE_ENABLED
      #   value: true
      # - key: CACHE_PROVIDER
      #   value: redis
      # - key: REDIS_URL # Define key only, set value in Render UI
      #   value: "" # Add empty value, will be overridden by dashboard secret

# Define the managed PostgreSQL database
databases:
  - name: it-helpdesk-db # Name for your database service on Render
    plan: free # Use the free tier (check Render pricing for limitations)
    postgresMajorVersion: 16 # Specify desired Postgres version (check Render supported versions)
    ipAllowList: [] # Allows connections from anywhere (Render services automatically have access) - adjust if needed

