# render.yaml  (version line is optional but recommended)
version: "1"

services:
  # ───────── NGINX REVERSE PROXY ─────────
  - name: it-helpdesk-proxy
    type: web
    runtime: docker          # <-- not "env"
    dockerContext: .
    dockerfilePath: ./nginx/Dockerfile
    envVars:
      - key: BACKEND_INTERNAL
        fromInternalAddress:
          serviceName: it-helpdesk-backend   # <-- corrected
          port: 8080
      - key: FRONTEND_INTERNAL
        fromInternalAddress:
          serviceName: it-helpdesk-frontend  # <-- corrected
          port: 80

  # ───────── FRONTEND ─────────
  - name: it-helpdesk-frontend
    type: web
    runtime: docker
    dockerContext: ./frontend
    dockerfilePath: ./Dockerfile   # path is relative to dockerContext

  # ───────── BACKEND ─────────
  - name: it-helpdesk-backend
    type: web
    runtime: docker
    dockerContext: .
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /healthz        # /api/healthz if that’s what you exposed
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: it-helpdesk-db
          property: connectionString
      - key: PORT
        value: "8080"
      # put real secrets in the dashboard or add `sync: false`
      - key: JWT_SECRET      ; sync: false
      - key: S3_ACCESS_KEY   ; sync: false
      - key: S3_SECRET_KEY   ; sync: false
      - key: RESEND_API_KEY  ; sync: false
      - key: PORTAL_BASE_URL ; value: "https://answersdesk.org"
      - key: EMAIL_FROM      ; value: "support@answersdesk.org"
      - key: S3_ENDPOINT     ; sync: false
      - key: S3_REGION       ; sync: false
      - key: S3_BUCKET       ; sync: false
      - key: S3_DISABLE_SSL  ; value: "false"

databases:
  - name: it-helpdesk-db
    postgresMajorVersion: 16
    ipAllowList: []
