# render.yaml
# ==================================================
# Infrastructure definition for the IT Helpdesk System on Render.
# ** UPDATED: Using fromService + internalHostname for proxy envVars **
# ==================================================

services:
  # Nginx Reverse Proxy (Public Web Service)
  - name: it-helpdesk-proxy # Name of your Nginx service
    type: web
    env: docker
    dockerContext: . # Build context is repo root
    dockerfilePath: ./nginx/Dockerfile # Path relative to repo root
    envVars:
      # --- Use fromService to get internal hostnames ---
      - key: BACKEND_HOST_INTERNAL # Variable to hold backend hostname
        fromService:
          type: web # Type of the source service
          name: it-helpdesk-backend # EXACT name of the backend service
          property: internalHostname # Property to retrieve
      - key: FRONTEND_HOST_INTERNAL # Variable to hold frontend hostname
        fromService:
          type: web # Type of the source service
          name: it-helpdesk-frontend # EXACT name of the frontend service
          property: internalHostname # Property to retrieve
      # --- End fromService definitions ---

  # Frontend Service (Web Service using Docker)
  - name: it-helpdesk-frontend # Ensure this name matches above
    type: web
    env: docker
    dockerContext: ./frontend # Build context is frontend directory
    dockerfilePath: ./Dockerfile # Path relative to dockerContext

  # Backend Service (Web Service using Docker)
  - name: it-helpdesk-backend # Ensure this name matches above
    type: web
    env: docker
    dockerContext: . # Build context is repo root
    dockerfilePath: ./backend/Dockerfile # Path relative to repo root
    healthCheckPath: /api/healthz # Define the health check path
    envVars:
      # --- Database URL (Injected by Render) ---
      - key: DATABASE_URL
        fromDatabase:
          name: it-helpdesk-db # Must match the database name defined below
          property: connectionString
      # --- Secrets (Values MUST be set in Render Dashboard Environment) ---
      - key: JWT_SECRET
        value: "" # Set value in Render UI
      - key: S3_ACCESS_KEY
        value: "" # Set value in Render UI
      - key: S3_SECRET_KEY
        value: "" # Set value in Render UI
      - key: RESEND_API_KEY
        value: "" # Set value in Render UI
      # --- Non-Secrets ---
      - key: PORT # Internal port the Go app listens on
        value: 8080 # Explicitly set to 8080
      - key: PORTAL_BASE_URL
        value: "" # Set value in Render UI (e.g., https://answersdesk.org)
      - key: EMAIL_FROM
        value: "" # Set value in Render UI (e.g., support@answersdesk.org)
      # --- Backblaze B2 Configuration ---
      - key: S3_ENDPOINT
        value: "" # Set value in Render UI
      - key: S3_REGION
        value: "" # Set value in Render UI
      - key: S3_BUCKET
        value: "" # Set value in Render UI
      - key: S3_DISABLE_SSL
        value: false

# Define the managed PostgreSQL database
databases:
  - name: it-helpdesk-db
    plan: free
    postgresMajorVersion: 16
    ipAllowList: []

